packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/*
  - packages/@core/base/*
  - apps/*
  - scripts/*

catalog:
  '@ast-grep/napi': ^0.33.1
  '@ctrl/tinycolor': ^4.1.0
  clsx: ^2.1.1
  pinia: ^2.3.0
  vue: ^3.5.13
  '@types/node': ^22.10.6
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vue/test-utils': ^2.4.6
  autoprefixer: ^10.4.20
  cross-env: ^7.0.3
  cspell: ^8.17.2
  happy-dom: ^16.6.0
  turbo: ^2.3.3
  typescript: ^5.7.3
  unbuild: ^3.3.1
  '@clack/prompts': ^0.9.1
  cac: ^6.7.14
  vite: ^6.0.7
  vitest: ^2.1.8
  vue-tsc: ^2.2.0
  tailwindcss: ^3.4.17
  rimraf: ^6.0.1
  lint-staged: ^15.3.0
  is-ci: ^4.1.0
  vue-router: ^4.5.0
  eslint-config-turbo: ^2.3.3
  eslint-plugin-command: ^2.1.0
  eslint-plugin-import-x: ^4.6.1
  '@eslint/js': ^9.18.0
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.20.0
  '@typescript-eslint/parser': ^8.20.0
  eslint: ^9.18.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-jsdoc: ^50.6.1
  eslint-plugin-jsonc: ^2.18.2
  eslint-plugin-n: ^17.15.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.6.0
  eslint-plugin-prettier: ^5.2.2
  eslint-plugin-regexp: ^2.7.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.32.0
  globals: ^15.14.0
  jsonc-eslint-parser: ^2.4.0
  vue-eslint-parser: ^9.4.3
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.9
  '@stylistic/stylelint-plugin': ^3.1.1
  stylelint-config-recess-order: ^5.1.1
  stylelint-scss: ^6.10.1
  postcss: ^8.5.1
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  stylelint: ^16.13.2
  stylelint-config-recommended: ^15.0.0
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^37.0.0
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  '@changesets/git': ^3.0.2
  '@manypkg/get-packages': ^2.2.2
  chalk: ^5.4.1
  consola: ^3.4.0
  dayjs: ^1.11.13
  execa: ^9.5.2
  find-up: ^7.0.0
  ora: ^8.1.1
  pkg-types: ^1.3.1
  '@intlify/unplugin-vue-i18n': ^6.0.3
  '@jspm/generator': ^2.4.2
  archiver: ^7.0.1
  cheerio: ^1.0.0
  get-port: ^7.1.0
  html-minifier-terser: ^7.0.2
  nitropack: ^2.10.4
  resolve.exports: ^2.0.3
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.7.0
  '@pnpm/workspace.read-manifest': ^1000.0.1
  '@types/archiver': ^6.0.3
  '@types/html-minifier-terser': ^7.0.2
  dotenv: ^16.4.7
  rollup: ^4.30.1
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.83.4
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.0
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  unplugin-element-plus: ^0.9.0
  '@vueuse/core': ^12.4.0
  element-plus: ^2.9.3
  '@iconify/json': ^2.2.295
  '@iconify/tailwind': ^1.2.0
  '@tailwindcss/nesting': ^0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.16
  cssnano: ^7.0.6
  postcss-antd-fixes: ^0.2.0
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.3
  tailwindcss-animate: ^1.0.7
  '@types/postcss-import': ^14.0.3